# Generated by Django 2.2.10 on 2020-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0004_auto_20200426_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='imagesp'),
        ),
    ]
