# Generated by Django 2.2.10 on 2020-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0005_auto_20200429_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='hilo_en_proceso',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
