# Generated by Django 2.2.10 on 2020-04-29 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maracay', '0007_pagosimagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosimagenes',
            name='user',
        ),
        migrations.AddField(
            model_name='pagosimagenes',
            name='user',
            field=models.ManyToManyField(related_name='user_pago', to=settings.AUTH_USER_MODEL),
        ),
    ]
