# Generated by Django 2.2.10 on 2020-04-29 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0008_auto_20200429_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosimagenes',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
