# Generated by Django 2.2.10 on 2020-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0009_auto_20200429_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosimagenes',
            name='user',
        ),
        migrations.AddField(
            model_name='pagosimagenes',
            name='email_user',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
