# Generated by Django 2.2.10 on 2020-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0010_auto_20200429_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricebs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30),
        ),
    ]
