# Generated by Django 2.2.10 on 2020-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0011_product_pricebs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolarBolivar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bolivar', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
