# Generated by Django 2.2.10 on 2020-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0013_auto_20200522_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseconfirmation',
            name='categoria_pago',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseconfirmation',
            name='lugarpago',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
