# Generated by Django 2.2.10 on 2020-07-15 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0014_auto_20200708_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
