# Generated by Django 2.2.10 on 2020-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0015_purchasehistory_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseconfirmation',
            name='categoria_pago',
        ),
        migrations.RemoveField(
            model_name='purchaseconfirmation',
            name='lugarpago',
        ),
        migrations.RemoveField(
            model_name='purchaseconfirmation',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='categoria_pago',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='lugarpago',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='moneda',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='payment_type',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
