# Generated by Django 2.2.10 on 2020-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0016_auto_20200715_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.ImageField(upload_to='imagesp/capturas/')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
