# Generated by Django 2.2.10 on 2020-08-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0017_pagos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.AddField(
            model_name='pagosimagenes',
            name='asunto',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagosimagenes',
            name='codigo_compra',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagosimagenes',
            name='mensaje',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagosimagenes',
            name='picture',
            field=models.ImageField(upload_to='imagesp/capturas/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Alias de la imagen', max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchaseconfirmation',
            name='code',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='categoria_pago',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='code_purchase',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='lugarpago',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='moneda',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='payment_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='total',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='code',
            field=models.CharField(max_length=1000),
        ),
    ]
