# Generated by Django 3.1 on 2020-08-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0018_auto_20200810_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
