# Generated by Django 3.1 on 2020-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0019_product_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Viveres'), (2, 'Frigorifico'), (3, 'Enlatados'), (4, 'Charcuteria'), (5, 'Carnes'), (6, 'Personales')], help_text='Seleccione una categoria del producto'),
        ),
    ]
