# Generated by Django 3.1 on 2020-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0020_auto_20200817_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolarbolivar',
            options={'verbose_name_plural': 'Tasa DolarBolivar'},
        ),
        migrations.AlterModelOptions(
            name='pagosimagenes',
            options={'verbose_name_plural': 'Imagenes de Pago'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfil de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='purchaseconfirmation',
            options={'verbose_name_plural': 'Confirmacion de compras'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name_plural': 'Historial de Compras'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='tokenpassword',
            options={'verbose_name_plural': 'Token Password'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name_plural': 'Herramientas'},
        ),
        migrations.RemoveField(
            model_name='tools',
            name='costoenvio',
        ),
        migrations.AddField(
            model_name='profile',
            name='costoenvio',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
