# Generated by Django 3.1 on 2020-10-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0021_auto_20201009_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='costoenvio',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
